Revert "Always set #![no_std]"
This reverts commit 4a53c9b238893348f12d20e24d3f4188462bc06f.

This caused a build error on Rust 1.40.

```
error[E0433]: failed to resolve: could not find `poll_with_tls_context` in `future`

error[E0433]: failed to resolve: could not find `from_generator` in `future`

error: aborting due to 2 previous errors
```